### ISSUE TITLE
Configuration names

### ISSUE THREAD

**Issue by martinkaberg** [nordcloud/aws-codepipeline-cfn-provider#3]
Some configuration names differ from the AWS cfn provider.

ParameterOverride => ParameterOverrides

Template => TemplatePath

Config =>  ConfigPath

Role => RoleArn

Operation => ActionMode

In ActionMode : 

    CHANGE_SET_EXECUTE executes a change set.

    CHANGE_SET_REPLACE creates the change set if it doesn't exist based on the stack name and template that you submit. If the change set exists, AWS CloudFormation deletes it, and then creates a new one.

    CREATE_UPDATE creates the stack if the specified stack doesn't exist. If the stack exists, AWS CloudFormation updates the stack. Use this action to update existing stacks. AWS CodePipeline won't replace the stack.

    DELETE_ONLY deletes a stack. If you specify a stack that doesn't exist, the action completes successfully without deleting a stack.

    REPLACE_ON_FAILURE creates a stack if the specified stack doesn't exist. If the stack exists and is in a failed state (reported as ROLLBACK_COMPLETE, ROLLBACK_FAILED, CREATE_FAILED, DELETE_FAILED, or UPDATE_ROLLBACK_FAILED), AWS CloudFormation deletes the stack and then creates a new stack. If the stack isn't in a failed state, AWS CloudFormation updates it. Use this action to automatically replace failed stacks without recovering or troubleshooting them. You would typically choose this mode for testing.

**Comment by martinkaberg** [comment]
Also this one.

Capabilities

    For stacks that contain certain resources, explicit acknowledgement that AWS CloudFormation might create or update those resources. For example, you must specify CAPABILITY_IAM if your stack template contains AWS Identity and Access Management (IAM) resources. For more information, see Acknowledging IAM Resources in AWS CloudFormation Templates.

    This property is conditional. If you have IAM resources in your stack template, you must specify this property.

**Comment by kpiotrowski** [comment]
done
