### ISSUE TITLE
Please add Capabilities option

### ISSUE THREAD

**Issue by martinkaberg** [nordcloud/aws-codepipeline-cfn-provider#4]
CAPABILITY_NAMED_IAM is now harded coded in lambda please add it as an option.

**Comment by tdi** [comment]
I think we can add both of them: CAPABILITY_IAM and CAPABILITY_NAMED_IAM  as options.

**Comment by martinkaberg** [comment]
It should just be a config option.

Capabilities

    For stacks that contain certain resources, explicit acknowledgement that AWS CloudFormation might create or update those resources. For example, you must specify CAPABILITY_IAM if your stack template contains AWS Identity and Access Management (IAM) resources. For more information, see Acknowledging IAM Resources in AWS CloudFormation Templates.

    This property is conditional. If you have IAM resources in your stack template, you must specify this property.

**Comment by kpiotrowski** [comment]
done
